
#=========================端口和项目名========================
server:
  port: 9098
  context-path: /cmfz_rest

spring:
  #=========================文件上传大小配置================
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #=========================数据库相关配置====================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  #=====================前缀和后缀===========================
  mvc:
    view:
      prefix: /
      suffix: .jsp

  #=====================配置全局日期响应格式=================
  jackson:
    date-format: "yyyy/MM/dd"




#==========================指定mapper文件的位置和别名==========
mybatis:
  mapper-locations: classpath:com/baizhi/cmfz/mapper/*.xml
  type-aliases-package: com.baizhi.cmfz.entity

# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list: #TrackerList参数,支持多个
    - 192.168.131.129:22122
